### ISSUE TITLE
syreclabs.com/go/faker ssl certificate expired

### ISSUE THREAD

**Issue by qiuker521** [dmgk/faker#10]
Is it the `syreclabs.com/go/faker` repo?

go get syreclabs.com/go/faker:

package syreclabs.com/go/faker: unrecognized import path "syreclabs.com/go/faker" (https fetch: Get https://syreclabs.com/go/faker?go-get=1: x509: certificate has expired or is not yet valid)

git clone :
fatal: unable to access 'http://syreclabs.com/go/faker/': SSL certificate problem: certificate has expired

**Comment by qiuker521** [comment]
set GIT_SSL_NO_VERIFY=true variable is an temp solution.

**Comment by dmgk** [comment]
Thanks for reporting, should be fixed now.

**Comment by pwarnes** [comment]
@dmgk This has happened again :(

**Comment by shcode** [comment]
@dmgk It's happening again, but with different message.

$ go get syreclabs.com/go/faker
go get syreclabs.com/go/faker: unrecognized import path "syreclabs.com/go/faker" (https fetch: Get https://syreclabs.com/go/faker?go-get=1: x509: certificate signed by unknown authority)
