### ISSUE TITLE
Deterministic Random

### ISSUE THREAD

**Issue by mpchadwick** [dmgk/faker#13]
stympy/faker allows supports deterministic random by allowing you to seed:

https://github.com/stympy/faker/blob/676788d63e7c2dc7033ca44b678a4ff30f0cf812/README.md#deterministic-random

This can be useful for example for testing.

**Comment by dmgk** [comment]
Thanks, I added faker.Seed(int64) - that should allows seeding the rng.

**Comment by mpchadwick** [comment]
Maybe helpful to update the README?
