### ISSUE TITLE
Certificate Expired

### ISSUE THREAD

**Issue by scottschreckengaust** [dmgk/faker#27]
The instructions at https://pkg.go.dev/syreclabs.com/go/faker may need to get updated or certificate renewed

The certificate, serial number `04:30:70:e1:06:dc:cd:cc:74:60:8c:73:cc:25:e7:5a:a0:94` expired Friday, February 24, 2023 at 12:39:43 AM

```
Get "https://syreclabs.com/go/faker?go-get=1": x509: “syreclabs.com” certificate is expired
```

**Comment by dmgk** [comment]
Thanks for the heads up, fixed.
