### ISSUE TITLE
Please tag a new release

### ISSUE THREAD

**Issue by AlekSi** [dmgk/faker#3]
Please make a new tag `v2.0.0` – there is a problem with dependency management after GitHub repository was moved (or GitHub account renamed?), and then import path was changed again: fc813babee880a354a5b13f631c9192d0849303a, https://github.com/dmgk/faker/compare/v1.0.0...master

Also please add [canonical import path](https://golang.org/doc/go1.4#canonicalimports) to make those problems visible and not subtle.

I squatted https://github.com/enodata to prevent anyone from creating https://github.com/enodata/faker and see the world burn.

**Comment by AlekSi** [comment]
FYI, I just squatted https://github.com/enodata to prevent anyone from creating https://github.com/enodata/faker and see the world burn.

**Comment by AlekSi** [comment]
I just found out that https://syreclabs.com/go/faker exists and not a vanity import path (not a redirect). That complicates things even more…
What is the best way to contribute and resolve this issue?

**Comment by dmgk** [comment]
Hi Alexey,

Thank you for your contributions. The canonical import path is `syreclabs.com/go/faker`, GitHub repo is a mirror.
